# Generated by Django 3.0.7 on 2020-08-05 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20200804_2200'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='session_client',
        ),
    ]
