# Generated by Django 3.0.7 on 2020-08-05 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_remove_customuser_session_client'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='is_host_and_renter',
        ),
    ]
