# Generated by Django 3.0.7 on 2020-08-07 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_remove_customuser_is_host_and_renter'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='picture',
            field=models.FileField(default='', upload_to='user_images'),
            preserve_default=False,
        ),
    ]
