# Generated by Django 3.0.7 on 2020-08-10 16:59

from django.conf import settings
import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('geolocation', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('street', models.CharField(max_length=100)),
                ('neighborhood', models.CharField(max_length=50)),
                ('transit', models.CharField(max_length=500)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('price', models.FloatField()),
                ('price_per_person', models.FloatField()),
                ('max_people', models.IntegerField()),
                ('beds', models.IntegerField()),
                ('bedrooms', models.IntegerField()),
                ('bathrooms', models.IntegerField()),
                ('rep_photo', models.FileField(blank=True, upload_to='room_images')),
                ('room_type', models.CharField(choices=[('PRIVATE ROOM', 'Private room'), ('SHARED ROOM', 'Shared room'), ('ENTIRE HOUSE', 'Entire home/apt')], default='ENTIRE HOUSE', max_length=20)),
                ('has_wifi', models.BooleanField(default=False)),
                ('has_heating', models.BooleanField(default=False)),
                ('has_freezer', models.BooleanField(default=False)),
                ('has_kitchen', models.BooleanField(default=False)),
                ('has_TV', models.BooleanField(default=False)),
                ('has_parking', models.BooleanField(default=False)),
                ('has_elevator', models.BooleanField(default=False)),
                ('has_living_room', models.BooleanField(default=False)),
                ('square_feet', models.FloatField()),
                ('description', models.TextField(max_length=2000)),
                ('smoking', models.BooleanField(default=False)),
                ('pets', models.BooleanField(default=False)),
                ('events', models.BooleanField(default=False)),
                ('minimum_nights', models.IntegerField()),
                ('is_reversed', models.BooleanField(default=False)),
                ('host_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='host', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
