# Generated by Django 3.0.7 on 2020-08-10 17:17

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoomRating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('rating', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(10.0)])),
                ('renter_id_rate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='renter_rate', to=settings.AUTH_USER_MODEL)),
                ('room_id_rate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_rate', to='rooms.Room')),
            ],
        ),
        migrations.CreateModel(
            name='RoomImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.FileField(blank=True, null=True, upload_to='user_images')),
                ('room_id_img', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_img', to='rooms.Room')),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('price', models.FloatField()),
                ('renter_id_res', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='renter_res', to=settings.AUTH_USER_MODEL)),
                ('room_id_res', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_res', to='rooms.Room')),
            ],
        ),
        migrations.CreateModel(
            name='HostRating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('rating', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(10.0)])),
                ('host_id_hostRate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='host_hostRate', to=settings.AUTH_USER_MODEL)),
                ('renter_id_hostRate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='renter_hostRate', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ClickedItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('renter_id_click', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='renter_click', to=settings.AUTH_USER_MODEL)),
                ('room_id_click', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_click', to='rooms.Room')),
            ],
        ),
    ]
