# Generated by Django 3.0.7 on 2020-08-11 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0003_auto_20200810_1719'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='end_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='room',
            name='start_date',
            field=models.DateField(),
        ),
    ]
