# Generated by Django 3.0.7 on 2020-08-13 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0005_auto_20200811_0826'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='city',
            field=models.CharField(default='Athens', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='room',
            name='country',
            field=models.CharField(default='Greece', max_length=50),
            preserve_default=False,
        ),
    ]
