# Generated by Django 3.0.7 on 2020-08-16 09:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rooms', '0006_auto_20200813_1452'),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchedItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('renter_id_search', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='renter_search', to=settings.AUTH_USER_MODEL)),
                ('room_id_search', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_search', to='rooms.Room')),
            ],
        ),
    ]
