# Generated by Django 3.0.7 on 2020-08-16 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0009_auto_20200816_1708'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomrating',
            name='date',
            field=models.DateField(),
        ),
    ]
