# Generated by Django 3.0.7 on 2020-08-20 15:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rooms', '0010_auto_20200816_2022'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecommendedItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('renter_id_rec', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='renter_recom', to=settings.AUTH_USER_MODEL)),
                ('room_id_red', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_recom', to='rooms.Room')),
            ],
        ),
    ]
