# Generated by Django 3.0.7 on 2020-08-20 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0011_recommendeditem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recommendeditem',
            old_name='room_id_red',
            new_name='room_id_rec',
        ),
    ]
