# Generated by Django 3.0.7 on 2020-08-22 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0014_auto_20200822_1523'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='name',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='room',
            name='transit',
            field=models.CharField(max_length=2000),
        ),
    ]
