# Generated by Django 3.0.7 on 2020-09-16 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0015_auto_20200822_1807'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='rep_photo',
            field=models.FileField(blank=True, null=True, upload_to='room_images'),
        ),
    ]
